export const Constant = {

    LIVE_STREAM_STARTED : 'LIVE_STREAM_STARTED',
    USER_FOLLOW : 'USER_FOLLOW',
    USER_JOIN_VIDEO : 'USER_JOIN_VIDEO',
    USER_GROUP_ADD : 'USER_GROUP_ADD',
    USER_GIFT : 'USER_GIFT',
    USER_TIP : 'USER_TIP',
    ALBUM_BUY : 'ALBUM_BUY',
    SWEET_TREAT_BUY : 'SWEET_TREAT_BUY',
    NEW_MESSAGE : 'NEW_MESSAGE'
}