export interface Register {
    name : string,
    modelname : string,
    dob : string,
    email : string,
    email_confirmation : string,
    password : string,
    password_confirmation :string
    gender : string,
    first_name : string,
    last_name : string,
    othername : string,
    official_document : string,
    id_proof  : string,
    holding_id_proof : string,
    payment_method : string,
    payoneer_email : string,
    payoneer_email_confirmation : string,	
    check_by_mail_address : string,
    check_by_mail_city : string,
    check_by_mail_state : string,
    check_by_mail_zip : string,
    check_by_mail_country : string,
    bank_name : string,
    routing_number : string,
    account_number : string,
    tax_id : string,
    agree_signup : string,
    performer_signup : string
}